Make tests a bit more verbose

diff --git a/lib/Ocamlrules.mk.in b/lib/Ocamlrules.mk.in
--- a/lib/Ocamlrules.mk.in
+++ b/lib/Ocamlrules.mk.in
@@ -67,7 +67,8 @@ $(test_byte_cmo): $(EXTERNAL_DEPS)
 
 test: $(test_native) $(test_byte)
 	for test in $^ ; do \
-	  ./$$test ; \
+	  echo -n $$test " " ; \
+	  (./$$test && echo "Passed") || echo "Failed" ; \
 	done
 
 %.cmxa: %.cmx
